spring:
  liquibase:
    default-schema: payments_local
    change-log: classpath:db/changelogs/changelog-local.xml
    liquibase-schema: payments

payments:
  data-source:
    schema: payments
    jdbc-url: jdbc:postgresql://localhost:5432/payments
    username: payments-user
    password: payments-passwd
    minPoolSize: 5
    maxPoolSize: 10
    pool-name: payments-service-pool
    dialect: POSTGRES