package org.bronco.payments.controllers.api

import com.fasterxml.jackson.annotation.JsonFormat
import java.time.LocalDate

//TODO: add request validation
class CreateCustomerRequest(
    val firstName: String,
    val middleName: String?,
    val lastName: String,
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "dd-MM-yyyy")
    val dateOfBirth: LocalDate,
    val nationality: String, //most probably an enum
    val login: String, //should be generated by the service
    val password: String, //should be nullable, to be set by other endpoint
    val email: String,
    val phoneNumber: String,
    val secondaryPhoneNumber: String?
)