plugins {
    id("org.jetbrains.kotlin.jvm") version("$kotlinVersion")
    id("org.springframework.boot") version("$springBootVersion")
    id("io.spring.dependency-management") version("$springDependencyManagement")
    id "org.jooq.jooq-codegen-gradle" version("$jooqVersion")
}

group = "org.bronco.payments"

kotlin {
    jvmToolchain {
        languageVersion = JavaLanguageVersion.of(22)
    }
}

dependencies {

    implementation("org.springframework.boot:spring-boot-starter-web") {
        exclude group: "org.springframework.boot", module: "spring-boot-starter-tomcat"
    }
    implementation("org.springframework.boot:spring-boot-starter-undertow")
    implementation("org.springframework.boot:spring-boot-starter-jooq")
    implementation "org.jooq:jooq-kotlin-coroutines:${jooqVersion}"
    implementation("jakarta.persistence:jakarta.persistence-api:3.2.0")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("io.micrometer:micrometer-registry-prometheus")
    runtimeOnly("org.springframework.boot:spring-boot-devtools")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core")
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:$openApiVersion")
    runtimeOnly("org.postgresql:postgresql")
    jooqCodegen("org.postgresql:postgresql")
    implementation("org.liquibase:liquibase-core")
    implementation("org.springframework.kafka:spring-kafka")
    implementation("com.googlecode.libphonenumber:libphonenumber:9.0.5")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
//    testImplementation("org.springframework.kafka:spring-kafka-test")

//    test containers dependencies
    testImplementation("org.testcontainers:postgresql:1.21.1")
}

test {
    useJUnitPlatform()
}

jooq {
    configuration {
        logging = "INFO"
        jdbc {
            driver = "org.postgresql.Driver"
            url="jdbc-url"
            user = "user"
            password = "password"
        }
        generator {
            name = "org.jooq.codegen.KotlinGenerator"
            database {
                name = "org.jooq.meta.postgres.PostgresDatabase"
                excludes = """
                    DATABASECHANGELOG
                  | DATABASECHANGELOGLOCK
                  | DEFAULT_CATALOG
                """
                inputSchema = "payments"
            }
            strategy {
                name = 'org.jooq.codegen.DefaultGeneratorStrategy'
            }
            generate {
                implicitJoinPathsAsKotlinProperties = true
                kotlinSetterJvmNameAnnotationsOnIsPrefix = true
                pojosAsKotlinDataClasses = true
                kotlinNotNullPojoAttributes = false
                kotlinNotNullRecordAttributes = false
                kotlinNotNullInterfaceAttributes = false
                kotlinDefaultedNullablePojoAttributes = true
                kotlinDefaultedNullableRecordAttributes = true
                routines = true
            }
            target {
                packageName = "${group}.schema.jooq.model"
                directory = 'target/generated-schema'
            }
        }

    }
}