/*
 * This file is generated by jOOQ.
 */
package org.bronco.payments.schema.jooq.model


import kotlin.collections.List

import org.bronco.payments.schema.jooq.model.tables.Customer
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Payments : SchemaImpl("payments", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>payments</code>
         */
        val PAYMENTS: Payments = Payments()
    }

    /**
     * The table <code>payments.customer</code>.
     */
    val CUSTOMER: Customer get() = Customer.CUSTOMER

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Customer.CUSTOMER
    )
}
