/*
 * This file is generated by jOOQ.
 */
package org.bronco.payments.schema.jooq.model


import kotlin.collections.List

import org.bronco.payments.schema.jooq.model.tables.Account
import org.bronco.payments.schema.jooq.model.tables.Customer
import org.bronco.payments.schema.jooq.model.tables.ProcessProgress
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Payments : SchemaImpl("payments", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>payments</code>
         */
        val PAYMENTS: Payments = Payments()
    }

    /**
     * The table <code>payments.account</code>.
     */
    val ACCOUNT: Account get() = Account.ACCOUNT

    /**
     * The table <code>payments.customer</code>.
     */
    val CUSTOMER: Customer get() = Customer.CUSTOMER

    /**
     * The table <code>payments.process_progress</code>.
     */
    val PROCESS_PROGRESS: ProcessProgress get() = ProcessProgress.PROCESS_PROGRESS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Account.ACCOUNT,
        Customer.CUSTOMER,
        ProcessProgress.PROCESS_PROGRESS
    )
}
