services:
  payments-db:
    container_name: payments_db
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_USER: payments-user
      POSTGRES_PASSWORD: payments-passwd
      POSTGRES_DB: payments
    ports:
      - "5432:5432"
    volumes:
      - payments-db:/var/lib/postgresql/data
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - payments-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d payments-schema" ]
      interval: 30s
      timeout: 10s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka-broker-1:
    image: confluentinc/cp-kafka:7.9.1
    hostname: kafka-broker-1
    ports:
      - "19092:19092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_INTERNAL://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  schema-registry:
#    image: confluentinc/cp-schema-registry:7.9.1
#    hostname: schema-registry
#    depends_on:
#      - kafka-broker-1
#    ports:
#      - "8081:8081"
#    environment:
#      SCHEMA_REGISTRY_HOST_NAME: schema-registry
#      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
#      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_INTERNAL://localhost:19092
#      SCHEMA_REGISTRY_DEBUG: 'true'

networks:
  payments-network:
    driver: bridge

volumes:
  payments-db: