/*
 * This file is generated by jOOQ.
 */
package org.bronco.payments.schema.jooq.model.tables.references


import org.bronco.payments.schema.jooq.model.tables.Customer
import org.bronco.payments.schema.jooq.model.tables.ProcessProgress



/**
 * The table <code>payments.customer</code>.
 */
val CUSTOMER: Customer = Customer.CUSTOMER

/**
 * The table <code>payments.process_progress</code>.
 */
val PROCESS_PROGRESS: ProcessProgress = ProcessProgress.PROCESS_PROGRESS
