/*
 * This file is generated by jOOQ.
 */
package org.bronco.payments.jooq.model.tables.references


import org.bronco.payments.jooq.model.tables.Customer



/**
 * The table <code>payments.customer</code>.
 */
val CUSTOMER: Customer = Customer.CUSTOMER
