/*
 * This file is generated by jOOQ.
 */
package org.bronco.payments.schema.jooq.model.tables


import org.bronco.payments.model.Currencies
import org.bronco.payments.repositories.account.model.AccountStatus
import java.math.BigDecimal
import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.bronco.payments.schema.jooq.model.Payments
import org.bronco.payments.schema.jooq.model.converters.AccountStatusConverter
import org.bronco.payments.schema.jooq.model.converters.CurrencyConverter
import org.bronco.payments.schema.jooq.model.keys.ACCOUNT__FK_CUSTOMER_ACCOUNT
import org.bronco.payments.schema.jooq.model.keys.PK_ACCOUNT_ID
import org.bronco.payments.schema.jooq.model.tables.Customer.CustomerPath
import org.bronco.payments.schema.jooq.model.tables.records.AccountRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Account(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AccountRecord>?,
    parentPath: InverseForeignKey<out Record, AccountRecord>?,
    aliased: Table<AccountRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AccountRecord>(
    alias,
    Payments.PAYMENTS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>payments.account</code>
         */
        val ACCOUNT: Account = Account()
        val ACCOUNT_STATUS_CONVERTER = AccountStatusConverter()
        val CURRENCY_CONVERTER = CurrencyConverter()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AccountRecord> = AccountRecord::class.java

    /**
     * The column <code>payments.account.id</code>.
     */
    val ID: TableField<AccountRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>payments.account.currency_code</code>.
     */
    val CURRENCY_CODE: TableField<AccountRecord, Currencies?> = createField(DSL.name("currency_code"), SQLDataType.VARCHAR(2).nullable(false), this, "", CURRENCY_CONVERTER)

    /**
     * The column <code>payments.account.balance</code>.
     */
    val BALANCE: TableField<AccountRecord, BigDecimal?> = createField(DSL.name("balance"), SQLDataType.NUMERIC(12, 2).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.NUMERIC)), this, "")

    /**
     * The column <code>payments.account.name</code>.
     */
    val NAME: TableField<AccountRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column <code>payments.account.status</code>.
     */
    val STATUS: TableField<AccountRecord, AccountStatus?> = createField(DSL.name("status"), SQLDataType.VARCHAR(15).nullable(false), this, "", ACCOUNT_STATUS_CONVERTER)

    /**
     * The column <code>payments.account.creation_date</code>.
     */
    val CREATION_DATE: TableField<AccountRecord, LocalDateTime?> = createField(DSL.name("creation_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>payments.account.modification_date</code>.
     */
    val MODIFICATION_DATE: TableField<AccountRecord, LocalDateTime?> = createField(DSL.name("modification_date"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>payments.account.customer_reference</code>.
     */
    val CUSTOMER_REFERENCE: TableField<AccountRecord, UUID?> = createField(DSL.name("customer_reference"), SQLDataType.UUID.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<AccountRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AccountRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AccountRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>payments.account</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>payments.account</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>payments.account</code> table reference
     */
    constructor(): this(DSL.name("account"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AccountRecord>?, parentPath: InverseForeignKey<out Record, AccountRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, ACCOUNT, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class AccountPath : Account, Path<AccountRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, AccountRecord>?, parentPath: InverseForeignKey<out Record, AccountRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<AccountRecord>): super(alias, aliased)
        override fun `as`(alias: String): AccountPath = AccountPath(DSL.name(alias), this)
        override fun `as`(alias: Name): AccountPath = AccountPath(alias, this)
        override fun `as`(alias: Table<*>): AccountPath = AccountPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Payments.PAYMENTS
    override fun getPrimaryKey(): UniqueKey<AccountRecord> = PK_ACCOUNT_ID
    override fun getReferences(): List<ForeignKey<AccountRecord, *>> = listOf(ACCOUNT__FK_CUSTOMER_ACCOUNT)

    private lateinit var _customer: CustomerPath

    /**
     * Get the implicit join path to the <code>payments.customer</code> table.
     */
    fun customer(): CustomerPath {
        if (!this::_customer.isInitialized)
            _customer = CustomerPath(this, ACCOUNT__FK_CUSTOMER_ACCOUNT, null)

        return _customer;
    }

    val customer: CustomerPath
        get(): CustomerPath = customer()
    override fun `as`(alias: String): Account = Account(DSL.name(alias), this)
    override fun `as`(alias: Name): Account = Account(alias, this)
    override fun `as`(alias: Table<*>): Account = Account(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Account = Account(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Account = Account(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Account = Account(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Account = Account(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Account = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Account = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Account = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Account = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Account = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Account = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Account = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Account = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Account = where(DSL.notExists(select))
}
