/*
 * This file is generated by jOOQ.
 */
package org.bronco.payments.jooq.model.tables


import java.time.LocalDate
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.bronco.payments.jooq.model.Payments
import org.bronco.payments.jooq.model.keys.PK_CUSTOMER_ID
import org.bronco.payments.jooq.model.keys.UQ_CUSTOMER_EMAIL
import org.bronco.payments.jooq.model.keys.UQ_CUSTOMER_LOGIN
import org.bronco.payments.jooq.model.keys.UQ_CUSTOMER_PHONE_NUMBER
import org.bronco.payments.jooq.model.tables.records.CustomerRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Customer(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CustomerRecord>?,
    parentPath: InverseForeignKey<out Record, CustomerRecord>?,
    aliased: Table<CustomerRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CustomerRecord>(
    alias,
    Payments.PAYMENTS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>payments.customer</code>
         */
        val CUSTOMER: Customer = Customer()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CustomerRecord> = CustomerRecord::class.java

    /**
     * The column <code>payments.customer.id</code>.
     */
    val ID: TableField<CustomerRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>payments.customer.first_name</code>.
     */
    val FIRST_NAME: TableField<CustomerRecord, String?> = createField(DSL.name("first_name"), SQLDataType.VARCHAR(40).nullable(false), this, "")

    /**
     * The column <code>payments.customer.middle_name</code>.
     */
    val MIDDLE_NAME: TableField<CustomerRecord, String?> = createField(DSL.name("middle_name"), SQLDataType.VARCHAR(40), this, "")

    /**
     * The column <code>payments.customer.last_name</code>.
     */
    val LAST_NAME: TableField<CustomerRecord, String?> = createField(DSL.name("last_name"), SQLDataType.VARCHAR(60).nullable(false), this, "")

    /**
     * The column <code>payments.customer.dob</code>.
     */
    val DOB: TableField<CustomerRecord, LocalDate?> = createField(DSL.name("dob"), SQLDataType.LOCALDATE.nullable(false), this, "")

    /**
     * The column <code>payments.customer.nationality</code>.
     */
    val NATIONALITY: TableField<CustomerRecord, String?> = createField(DSL.name("nationality"), SQLDataType.VARCHAR(2).nullable(false), this, "")

    /**
     * The column <code>payments.customer.login</code>.
     */
    val LOGIN: TableField<CustomerRecord, String?> = createField(DSL.name("login"), SQLDataType.VARCHAR(10).nullable(false), this, "")

    /**
     * The column <code>payments.customer.password</code>.
     */
    val PASSWORD: TableField<CustomerRecord, String?> = createField(DSL.name("password"), SQLDataType.VARCHAR(45).nullable(false), this, "")

    /**
     * The column <code>payments.customer.email</code>.
     */
    val EMAIL: TableField<CustomerRecord, String?> = createField(DSL.name("email"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>payments.customer.phone_number</code>.
     */
    val PHONE_NUMBER: TableField<CustomerRecord, String?> = createField(DSL.name("phone_number"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>payments.customer.secondary_phone_number</code>.
     */
    val SECONDARY_PHONE_NUMBER: TableField<CustomerRecord, String?> = createField(DSL.name("secondary_phone_number"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<CustomerRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CustomerRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CustomerRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>payments.customer</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>payments.customer</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>payments.customer</code> table reference
     */
    constructor(): this(DSL.name("customer"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Payments.PAYMENTS
    override fun getPrimaryKey(): UniqueKey<CustomerRecord> = PK_CUSTOMER_ID
    override fun getUniqueKeys(): List<UniqueKey<CustomerRecord>> = listOf(UQ_CUSTOMER_EMAIL, UQ_CUSTOMER_LOGIN, UQ_CUSTOMER_PHONE_NUMBER)
    override fun `as`(alias: String): Customer = Customer(DSL.name(alias), this)
    override fun `as`(alias: Name): Customer = Customer(alias, this)
    override fun `as`(alias: Table<*>): Customer = Customer(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Customer = Customer(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Customer = Customer(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Customer = Customer(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Customer = Customer(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Customer = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Customer = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Customer = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Customer = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Customer = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Customer = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Customer = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Customer = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Customer = where(DSL.notExists(select))
}
