/*
 * This file is generated by jOOQ.
 */
package org.bronco.payments.schema.jooq.model.tables


import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.Collection

import org.bronco.payments.schema.jooq.model.Payments
import org.bronco.payments.schema.jooq.model.keys.PK_PROCESS_PROGRESS_KEY
import org.bronco.payments.schema.jooq.model.tables.records.ProcessProgressRecord
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ProcessProgress(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ProcessProgressRecord>?,
    parentPath: InverseForeignKey<out Record, ProcessProgressRecord>?,
    aliased: Table<ProcessProgressRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ProcessProgressRecord>(
    alias,
    Payments.PAYMENTS,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>payments.process_progress</code>
         */
        val PROCESS_PROGRESS: ProcessProgress = ProcessProgress()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ProcessProgressRecord> = ProcessProgressRecord::class.java

    /**
     * The column <code>payments.process_progress.process_id</code>.
     */
    val PROCESS_ID: TableField<ProcessProgressRecord, UUID?> = createField(DSL.name("process_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>payments.process_progress.process_name</code>.
     */
    val PROCESS_NAME: TableField<ProcessProgressRecord, String?> = createField(DSL.name("process_name"), SQLDataType.VARCHAR(25).nullable(false), this, "")

    /**
     * The column <code>payments.process_progress.progress</code>.
     */
    val PROGRESS: TableField<ProcessProgressRecord, String?> = createField(DSL.name("progress"), SQLDataType.VARCHAR(25).nullable(false), this, "")

    /**
     * The column <code>payments.process_progress.entity_id</code>.
     */
    val ENTITY_ID: TableField<ProcessProgressRecord, UUID?> = createField(DSL.name("entity_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>payments.process_progress.details</code>.
     */
    val DETAILS: TableField<ProcessProgressRecord, String?> = createField(DSL.name("details"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>payments.process_progress.creation_date</code>.
     */
    val CREATION_DATE: TableField<ProcessProgressRecord, LocalDateTime?> = createField(DSL.name("creation_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>payments.process_progress.modification_date</code>.
     */
    val MODIFICATION_DATE: TableField<ProcessProgressRecord, LocalDateTime?> = createField(DSL.name("modification_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ProcessProgressRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ProcessProgressRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ProcessProgressRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>payments.process_progress</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>payments.process_progress</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>payments.process_progress</code> table reference
     */
    constructor(): this(DSL.name("process_progress"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Payments.PAYMENTS
    override fun getPrimaryKey(): UniqueKey<ProcessProgressRecord> = PK_PROCESS_PROGRESS_KEY
    override fun `as`(alias: String): ProcessProgress = ProcessProgress(DSL.name(alias), this)
    override fun `as`(alias: Name): ProcessProgress = ProcessProgress(alias, this)
    override fun `as`(alias: Table<*>): ProcessProgress = ProcessProgress(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ProcessProgress = ProcessProgress(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ProcessProgress = ProcessProgress(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ProcessProgress = ProcessProgress(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ProcessProgress = ProcessProgress(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ProcessProgress = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ProcessProgress = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ProcessProgress = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ProcessProgress = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ProcessProgress = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ProcessProgress = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ProcessProgress = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ProcessProgress = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ProcessProgress = where(DSL.notExists(select))
}
