/*
 * This file is generated by jOOQ.
 */
package org.bronco.payments.schema.jooq.model.tables.records


import java.math.BigDecimal
import java.time.LocalDateTime
import java.util.UUID

import org.bronco.payments.schema.jooq.model.tables.Account
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AccountRecord() : UpdatableRecordImpl<AccountRecord>(Account.ACCOUNT) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var currencyCode: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var balance: BigDecimal?
        set(value): Unit = set(2, value)
        get(): BigDecimal? = get(2) as BigDecimal?

    open var name: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var status: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var creationDate: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var modificationDate: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    open var customerReference: UUID?
        set(value): Unit = set(7, value)
        get(): UUID? = get(7) as UUID?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised AccountRecord
     */
    constructor(id: UUID? = null, currencyCode: String? = null, balance: BigDecimal? = null, name: String? = null, status: String? = null, creationDate: LocalDateTime? = null, modificationDate: LocalDateTime? = null, customerReference: UUID? = null): this() {
        this.id = id
        this.currencyCode = currencyCode
        this.balance = balance
        this.name = name
        this.status = status
        this.creationDate = creationDate
        this.modificationDate = modificationDate
        this.customerReference = customerReference
        resetChangedOnNotNull()
    }
}
