/*
 * This file is generated by jOOQ.
 */
package org.bronco.payments.schema.jooq.model.tables.records


import java.time.LocalDate
import java.util.UUID

import org.bronco.payments.schema.jooq.model.tables.Customer
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CustomerRecord() : UpdatableRecordImpl<CustomerRecord>(Customer.CUSTOMER) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var firstName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var middleName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var lastName: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var dob: LocalDate?
        set(value): Unit = set(4, value)
        get(): LocalDate? = get(4) as LocalDate?

    open var nationality: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var login: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var password: String?
        set(value): Unit = set(7, value)
        get(): String? = get(7) as String?

    open var email: String?
        set(value): Unit = set(8, value)
        get(): String? = get(8) as String?

    open var phoneNumber: String?
        set(value): Unit = set(9, value)
        get(): String? = get(9) as String?

    open var secondaryPhoneNumber: String?
        set(value): Unit = set(10, value)
        get(): String? = get(10) as String?

    open var residencyCountryCode: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised CustomerRecord
     */
    constructor(id: UUID? = null, firstName: String? = null, middleName: String? = null, lastName: String? = null, dob: LocalDate? = null, nationality: String? = null, login: String? = null, password: String? = null, email: String? = null, phoneNumber: String? = null, secondaryPhoneNumber: String? = null, residencyCountryCode: String? = null): this() {
        this.id = id
        this.firstName = firstName
        this.middleName = middleName
        this.lastName = lastName
        this.dob = dob
        this.nationality = nationality
        this.login = login
        this.password = password
        this.email = email
        this.phoneNumber = phoneNumber
        this.secondaryPhoneNumber = secondaryPhoneNumber
        this.residencyCountryCode = residencyCountryCode
        resetChangedOnNotNull()
    }
}
