/*
 * This file is generated by jOOQ.
 */
package org.bronco.payments.schema.jooq.model.tables.records


import java.time.LocalDateTime
import java.util.UUID

import org.bronco.payments.schema.jooq.model.tables.ProcessProgress
import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ProcessProgressRecord() : UpdatableRecordImpl<ProcessProgressRecord>(ProcessProgress.PROCESS_PROGRESS) {

    open var processId: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var processName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var progress: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var entityId: UUID?
        set(value): Unit = set(3, value)
        get(): UUID? = get(3) as UUID?

    open var details: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var creationDate: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    open var modificationDate: LocalDateTime?
        set(value): Unit = set(6, value)
        get(): LocalDateTime? = get(6) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<UUID?, String?> = super.key() as Record2<UUID?, String?>

    /**
     * Create a detached, initialised ProcessProgressRecord
     */
    constructor(processId: UUID? = null, processName: String? = null, progress: String? = null, entityId: UUID? = null, details: String? = null, creationDate: LocalDateTime? = null, modificationDate: LocalDateTime? = null): this() {
        this.processId = processId
        this.processName = processName
        this.progress = progress
        this.entityId = entityId
        this.details = details
        this.creationDate = creationDate
        this.modificationDate = modificationDate
        resetChangedOnNotNull()
    }
}
