/*
 * This file is generated by jOOQ.
 */
package org.bronco.payments.schema.jooq.model.keys


import org.bronco.payments.schema.jooq.model.tables.Customer
import org.bronco.payments.schema.jooq.model.tables.records.CustomerRecord
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val PK_CUSTOMER_ID: UniqueKey<CustomerRecord> = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("pk_customer_id"), arrayOf(Customer.CUSTOMER.ID), true)
val UQ_CUSTOMER_EMAIL: UniqueKey<CustomerRecord> = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("uq_customer_email"), arrayOf(Customer.CUSTOMER.EMAIL), true)
val UQ_CUSTOMER_LOGIN: UniqueKey<CustomerRecord> = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("uq_customer_login"), arrayOf(Customer.CUSTOMER.LOGIN), true)
val UQ_CUSTOMER_PHONE_NUMBER: UniqueKey<CustomerRecord> = Internal.createUniqueKey(Customer.CUSTOMER, DSL.name("uq_customer_phone_number"), arrayOf(Customer.CUSTOMER.PHONE_NUMBER), true)
